quarkus.http.host=0.0.0.0
quarkus.http.port=8080
# --- CONFIGURACIÓN PARA NGINX / PROXY ---
# 1. Avisar a Quarkus que confíe en los headers de Nginx (X-Forwarded-For)
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded-host=true
# 2. Seguridad de WebSocket
# Evita que mensajes gigantes saturen tu memoria (DoS)
quarkus.http.websocket.max-frame-size=65536
# 3. (Opcional) Si quieres ver logs detallados de las conexiones en consola
quarkus.log.level=INFO
quarkus.log.category."edu.itson.jackMurrieta".level=DEBUG