worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    limit_conn_zone $binary_remote_addr zone=addr:10m;
    limit_req_zone  $binary_remote_addr zone=req_limit:10m rate=10r/s;
# CORS Con subdoinios
#     map $http_origin $allowed_origin {
#         default 0;
#         ~^http://localhost$ 1;
#         ~^https://.*\.ngrok-free\.dev$ 1;
#     }

    map $http_origin $cors_origin {
        default "$http_origin";
    }

    upstream quarkus_backend {
        server 127.0.0.1:8080;
        keepalive 32;
    }

    server {
        listen 80;
        server_name localhost;

        access_log logs/chat_access.log;
        error_log  logs/chat_error.log;

        location /chat {

            if ($http_upgrade != "websocket") {
                return 400;
            }

            # Preflight OPTIONS
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin  $cors_origin;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
                add_header Access-Control-Allow-Headers "Upgrade, Connection, Origin";
                return 204;
            }

            # Headers CORS
            add_header Access-Control-Allow-Origin  $cors_origin always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Upgrade, Connection, Origin" always;

            limit_conn addr 5;
            limit_req zone=req_limit burst=20;

            proxy_pass http://quarkus_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}