package views;

import interfaces.IEnviador;
import interfaces.ISuscriptor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import valdez.alejandro.entidades.Message;
import valdez.alejandro.entidades.User;

/**
 *
 * @author juanpheras
 */
public class ChatLobby extends javax.swing.JFrame implements ISuscriptor {

    private IEnviador enviador;
    private String usuarioActual;

    private List<User> usuariosActuales = new ArrayList<>();

    /**
     * Creates new form Register
     */
    public ChatLobby() {
        initComponents();
        setLocationRelativeTo(this);

        listUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUsuariosValueChanged(evt);
            }
        });

    }

    public void setEnviador(IEnviador enviador) {
        this.enviador = enviador;
    }

    private boolean nombreYaExiste(String nombre) {
        for (User user : usuariosActuales) {
            if (user.getUsername().equalsIgnoreCase(nombre)) {
                return true;
            }
        }
        return false;
    }

    public void iniciarSesion() {
        solicitarNombreUsuario();
    }

    private void solicitarNombreUsuario() {
        boolean valido = false;

        while (!valido) {
            String nombre = JOptionPane.showInputDialog(this, "Ingresa tu nombre de usuario:");

            if (nombre == null) {
                System.exit(0);
            }

            nombre = nombre.trim();

            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
                continue;
            }

//            if (nombreYaExiste(nombre)) {
//                JOptionPane.showMessageDialog(this, "Ese nombre ya está en uso.");
//                continue;
//            }

            this.usuarioActual = nombre;
            valido = true;
        }

        Message connectMsg = new Message(
                usuarioActual,
                null,
                "Se conectó al chat",
                valdez.alejandro.enums.MessageType.CONNECT
        );

        enviador.enviarMensajeDesdeView(connectMsg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblMensaje = new javax.swing.JLabel();
        lblDestinoMsj = new javax.swing.JLabel();
        textMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnMensajeTodos = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGeneral.setBackground(new java.awt.Color(240, 240, 240));

        jScrollPane1.setViewportView(listUsuarios);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lblMensaje.setText("Mensaje para: ");

        lblDestinoMsj.setText("User");

        textMensaje.setText("...");
        textMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMensajeActionPerformed(evt);
            }
        });

        btnEnviar.setBackground(new java.awt.Color(172, 245, 172));
        btnEnviar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnMensajeTodos.setText("Mensaje para todos");
        btnMensajeTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajeTodosActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitulo.setText("Desktop Chat");

        lblChat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblChat.setText("Chat");

        lblUsuarios.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblUsuarios.setText("Usuarios conectados");

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnMensajeTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                            .addComponent(lblUsuarios))
                        .addGap(37, 37, 37)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChat)
                            .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlGeneralLayout.createSequentialGroup()
                                    .addComponent(lblMensaje)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblDestinoMsj)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChat)
                    .addComponent(lblUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMensaje)
                    .addComponent(lblDestinoMsj)
                    .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)
                    .addComponent(btnMensajeTodos))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMensajeActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String contenido = textMensaje.getText().trim();

        if (contenido.isEmpty()) {
            onError("Escribe un mensaje");
            return;
        }

        boolean paraTodos = btnMensajeTodos.isSelected();
        String destino = paraTodos ? null : listUsuarios.getSelectedValue();

        if (!paraTodos && destino == null) {
            onError("Selecciona un usuario o usa 'Mensaje para todos'.");
            return;
        }

        Message mensaje = new Message(
                usuarioActual,
                destino,
                contenido,
                paraTodos
                        ? valdez.alejandro.enums.MessageType.BROADCAST
                        : valdez.alejandro.enums.MessageType.PRIVATE
        );

        enviador.enviarMensajeDesdeView(mensaje);

        textMensaje.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * Método para ajustar el destinatario al chat global. Si hay un usuario
     * seleccionado lo deselecciona.
     *
     * @param evt
     */
    private void btnMensajeTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajeTodosActionPerformed
        if (btnMensajeTodos.isSelected()) {
            listUsuarios.clearSelection();
            lblDestinoMsj.setText("Todos");
        } else {
            lblDestinoMsj.setText("User");
        }
    }//GEN-LAST:event_btnMensajeTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JToggleButton btnMensajeTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblDestinoMsj;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JList<String> listUsuarios;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JTextField textMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onMensajeRecibido(Message mensaje) {
        SwingUtilities.invokeLater(() -> {
            String texto;

            if (mensaje.getTo() == null) {
                texto = mensaje.getFrom() + " (Todos): " + mensaje.getContent();
            } else {
                texto = mensaje.getFrom() + " (Privado): " + mensaje.getContent();
            }

            jTextArea1.append(texto + "\n");
        });
    }

    @Override
    public void onListaUsuariosActualizada(List<User> usuarios) {
        SwingUtilities.invokeLater(() -> {
            usuariosActuales = usuarios; // 🔥 aquí se actualiza

            DefaultListModel<String> model = new DefaultListModel<>();
            for (User u : usuarios) {
                model.addElement(u.getUsername());
            }

            listUsuarios.setModel(model);
        });
    }

    @Override
    public void onError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Listener para cuando se seleccione un usuario para ajustar el
     * destinatario. Además se deselecciona el botón de "Mensaje para todos"
     *
     * @param evt
     */
    private void listUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            String seleccionado = listUsuarios.getSelectedValue();

            if (seleccionado != null) {
                lblDestinoMsj.setText(seleccionado);
                btnMensajeTodos.setSelected(false);
            }
        }
    }

//    private void btnMensajeTodosActionPerformed(java.awt.event.ActionEvent evt) {
//        if (btnMensajeTodos.isSelected()) {
//            listUsuarios.clearSelection();
//            lblDestinoMsj.setText("Todos");
//        } else {
//            lblDestinoMsj.setText("User");
//        }
//    }
}
